const KEY='wordly-words-v2',THEME='wordly-theme-v2';
const starter=[['apple','яблоко','I eat an apple every day.'],['beautiful','красивый','This place is very beautiful.'],['important','важный','This is an important question.'],['difficult','сложный','English is not difficult.'],['easy','лёгкий','This exercise is easy.'],['good','хороший','It is a good idea.'],['friend','друг','He is my best friend.'],['family','семья','I love my family.'],['water','вода','Please drink some water.'],['house','дом','We live in a small house.']];
let words=JSON.parse(localStorage.getItem(KEY)||'null');if(!words){words=starter.map((x,i)=>({id:'s'+i,en:x[0],ru:x[1],example:x[2],note:'',level:0,nextReview:Date.now(),createdAt:Date.now()}));save()}
function save(){localStorage.setItem(KEY,JSON.stringify(words))}function id(){return 'w'+Date.now()+Math.random().toString(16).slice(2)}function mastered(w){return w.level>=5}function due(w){return w.nextReview<=Date.now()}function escape(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(name==='screen-cards')renderCards();if(name==='screen-progress')renderProgress();if(name==='screen-learn')renderLearn();if(name==='screen-test')startTest();scrollTo(0,0)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)screen(b.dataset.screen)});
function renderCards(){const q=document.getElementById('search-input').value.trim().toLowerCase();const list=document.getElementById('cards-list');const arr=words.filter(w=>(w.en+' '+w.ru).toLowerCase().includes(q));document.getElementById('all-count').textContent=words.length;document.getElementById('learn-count').textContent=words.filter(w=>!mastered(w)).length;document.getElementById('mastered-count').textContent=words.filter(mastered).length;if(!arr.length){list.innerHTML='<div class="empty">Ничего не найдено</div>';return}list.innerHTML=arr.map(w=>`<button class="word-row" data-id="${w.id}"><div class="main"><b>${escape(w.en)}</b><small>${escape(w.ru)}</small></div><span class="level-dot ${mastered(w)?'mastered':''}">${mastered(w)?'✓':'ур. '+w.level}</span></button>`).join('');list.querySelectorAll('.word-row').forEach(b=>b.onclick=()=>detail(b.dataset.id))}
document.getElementById('search-input').addEventListener('input',renderCards);
function detail(id){const w=words.find(x=>x.id===id);if(!w)return;document.getElementById('detail-content').innerHTML=`<div class="detail-card"><div class="word-big">${escape(w.en)}</div><div class="translation">${escape(w.ru)}</div><hr><div class="detail-meta">Пример</div><p>${escape(w.example||'—')}</p>${w.note?`<div class="detail-meta">Заметка</div><p>${escape(w.note)}</p>`:''}<div class="detail-meta">Уровень ${w.level} · ${mastered(w)?'Выучено':'Следующее повторение: '+new Date(w.nextReview).toLocaleDateString('ru-RU')}</div><div class="detail-actions"><button onclick="speak('${escape(w.en).replaceAll("'","\\'")}')">◖ Произнести</button><button onclick="deleteWord('${w.id}')">Удалить</button></div></div>`;document.getElementById('detail-edit').onclick=()=>editWord(w.id);screen('screen-detail')}
window.speak=t=>{if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(t);u.lang='en-US';speechSynthesis.cancel();speechSynthesis.speak(u)};
window.deleteWord=i=>{if(confirm('Удалить карточку?')){words=words.filter(w=>w.id!==i);save();screen('screen-cards')}};
function editWord(i){const w=words.find(x=>x.id===i);if(!w)return;document.getElementById('input-en').value=w.en;document.getElementById('input-ru').value=w.ru;document.getElementById('input-example').value=w.example;document.getElementById('input-note').value=w.note;document.getElementById('word-form').dataset.edit=i;screen('screen-add')}
document.getElementById('word-form').addEventListener('submit',e=>{e.preventDefault();const en=document.getElementById('input-en').value.trim(),ru=document.getElementById('input-ru').value.trim(),example=document.getElementById('input-example').value.trim(),note=document.getElementById('input-note').value.trim(),edit=e.target.dataset.edit;if(edit){const w=words.find(x=>x.id===edit);Object.assign(w,{en,ru,example,note});delete e.target.dataset.edit}else words.push({id:id(),en,ru,example,note,level:0,nextReview:Date.now(),createdAt:Date.now()});save();e.target.reset();screen('screen-cards')});
document.getElementById('save-word').onclick=()=>document.getElementById('word-form').requestSubmit();
let learnId=null,learnShown=false;function renderLearn(){let dueWords=words.filter(due);if(!dueWords.length)dueWords=words.filter(w=>!mastered(w));if(!dueWords.length){document.getElementById('learn-word').textContent='Нет слов';document.getElementById('learn-hint').textContent='Добавьте карточку';return}const w=dueWords[0];learnId=w.id;learnShown=false;document.getElementById('learn-word').textContent=w.en;document.getElementById('learn-translation').textContent=w.ru;document.getElementById('learn-example').textContent=w.example||'';document.getElementById('learn-answer').classList.add('hidden');document.getElementById('learn-hint').classList.remove('hidden');document.getElementById('learn-progress-label').textContent=`${Math.min(1,dueWords.length)} / ${dueWords.length}`;document.getElementById('learn-progress-bar').style.width='25%'}
document.getElementById('study-card').onclick=()=>{learnShown=!learnShown;document.getElementById('learn-answer').classList.toggle('hidden',!learnShown);document.getElementById('learn-hint').classList.toggle('hidden',learnShown)};document.getElementById('learn-speak').onclick=e=>{e.stopPropagation();const w=words.find(x=>x.id===learnId);if(w)speak(w.en)};
function answer(knew){const w=words.find(x=>x.id===learnId);if(!w)return;w.level=knew?Math.min(5,w.level+1):Math.max(0,w.level-1);const days=[0,1,3,7,14,30][w.level];w.nextReview=Date.now()+days*86400000;save();renderLearn()}document.getElementById('learn-yes').onclick=()=>answer(true);document.getElementById('learn-no').onclick=()=>answer(false);
let testWords=[],testIndex=0;function startTest(){testWords=words.slice().sort(()=>Math.random()-.5).slice(0,Math.min(10,words.length));testIndex=0;showTest()}function showTest(){const w=testWords[testIndex];if(!w){document.getElementById('test-word').textContent='Готово!';document.getElementById('test-answer').style.display='none';document.getElementById('test-check').style.display='none';document.getElementById('test-result').textContent='Тест завершён';return}document.getElementById('test-label').textContent=`${testIndex+1} / ${testWords.length}`;document.getElementById('test-word').textContent=w.en;document.getElementById('test-answer').value='';document.getElementById('test-result').textContent='';document.getElementById('test-bar').style.width=((testIndex)/testWords.length*100)+'%'}document.getElementById('test-check').onclick=()=>{const w=testWords[testIndex];const a=document.getElementById('test-answer').value.trim().toLowerCase();if(!a)return;const ok=a===w.ru.toLowerCase();document.getElementById('test-result').textContent=ok?'✓ Правильно!':'✕ Правильный ответ: '+w.ru;if(ok)w.level=Math.min(5,w.level+1);w.nextReview=Date.now()+([0,1,3,7,14,30][w.level])*86400000;save();setTimeout(()=>{testIndex++;showTest()},700)};
function renderProgress(){const m=words.filter(mastered).length,l=words.length-m;document.getElementById('p-mastered').textContent=m;document.getElementById('p-learning').textContent=l;document.getElementById('p-total').textContent=words.length;document.getElementById('chart').innerHTML=[22,18,27,20,12,24,8].map((v,i)=>`<div class="bar" style="height:${v*4}px"><small>${'Пн Вт Ср Чт Пт Сб Вс'.split(' ')[i]}</small></div>`).join('');const total=words.length||1;document.getElementById('levels').innerHTML=[0,1,2,3,4,5].map(x=>{const n=words.filter(w=>w.level===x).length;return `<div class="level-stat"><span>${x===5?'Выучено':'Уровень '+x}</span><div class="track"><span style="width:${n/total*100}%"></span></div><b>${n}</b></div>`}).join('')}
const themeLabel={'system':'Системная','light':'Светлая','dark':'Тёмная'};function applyTheme(t){document.documentElement.dataset.theme=t;document.getElementById('theme-label').textContent=themeLabel[t]||'Системная'}function setTheme(t){localStorage.setItem(THEME,t);applyTheme(t);document.querySelector('.theme-panel').classList.remove('open')}applyTheme(localStorage.getItem(THEME)||'system');document.querySelector('.profile').onclick=()=>{};document.querySelector('.settings-list button').onclick=()=>document.querySelector('.theme-panel').classList.toggle('open');document.querySelectorAll('.theme-panel button').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
document.getElementById('reset-btn').onclick=()=>{if(confirm('Сбросить уровни всех слов?')){words.forEach(w=>{w.level=0;w.nextReview=Date.now()});save();renderProgress()}};
document.getElementById('export-btn').onclick=()=>{const blob=new Blob([JSON.stringify(words,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wordly-backup.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('import-btn').onclick=()=>document.getElementById('import-file').click();document.getElementById('import-file').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(Array.isArray(x)){words=x;save();screen('screen-cards')}}catch{alert('Не удалось импортировать файл')}};r.readAsText(f)};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
